// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe6ysqbUHwXhxujyFLUAImBKWKx4iIbu4',
    appId: '1:498852705956:web:1c554d49d8feed180e1831',
    messagingSenderId: '498852705956',
    projectId: 'deliveryapp-e36e3',
    authDomain: 'deliveryapp-e36e3.firebaseapp.com',
    storageBucket: 'deliveryapp-e36e3.firebasestorage.app',
    measurementId: 'G-385KG9Z7HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIQ3xaM9UBN7Zaho0sMHq1wXI4mLFMas',
    appId: '1:498852705956:android:f56ae1f8bda1b9ee0e1831',
    messagingSenderId: '498852705956',
    projectId: 'deliveryapp-e36e3',
    storageBucket: 'deliveryapp-e36e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrUi1zIXpDmjXDlDf79PYfP81cakL7e4',
    appId: '1:498852705956:ios:6087348bb6fbc4c90e1831',
    messagingSenderId: '498852705956',
    projectId: 'deliveryapp-e36e3',
    storageBucket: 'deliveryapp-e36e3.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLrUi1zIXpDmjXDlDf79PYfP81cakL7e4',
    appId: '1:498852705956:ios:6087348bb6fbc4c90e1831',
    messagingSenderId: '498852705956',
    projectId: 'deliveryapp-e36e3',
    storageBucket: 'deliveryapp-e36e3.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe6ysqbUHwXhxujyFLUAImBKWKx4iIbu4',
    appId: '1:498852705956:web:0aa53f55aaae4a340e1831',
    messagingSenderId: '498852705956',
    projectId: 'deliveryapp-e36e3',
    authDomain: 'deliveryapp-e36e3.firebaseapp.com',
    storageBucket: 'deliveryapp-e36e3.firebasestorage.app',
    measurementId: 'G-L7XMJ0JJNJ',
  );
}
